project_id = "yneaxuokgfqyoomycjam"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.track-zip]
verify_jwt = true

[functions.sync-subscription]
verify_jwt = false

[functions.verify-checkout]
verify_jwt = false

[functions.check-admin]
verify_jwt = false

[functions.admin-blog]
verify_jwt = false

[functions.blog-track-view]
verify_jwt = false

[functions.rss]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.google-drive-export]
verify_jwt = false
