project_id = "yneaxuokgfqyoomycjam"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.track-zip]
verify_jwt = true

[functions.sync-subscription]
verify_jwt = false

[functions.verify-checkout]
verify_jwt = false
